
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 21 21:27:14 CST 2022
//----------------------------------------------------

package Compiladorcito;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tkn_caracter = 34;
  public static final int tkn_char = 26;
  public static final int tkn_puntocoma = 28;
  public static final int tkn_opmulti = 3;
  public static final int tkn_printf = 20;
  public static final int tkn_cadena = 33;
  public static final int tkn_break = 4;
  public static final int tkn_ternario = 29;
  public static final int tkn_coma = 31;
  public static final int tkn_increment = 22;
  public static final int tkn_opmod = 5;
  public static final int tkn_dospuntos = 24;
  public static final int tkn_parentesisde = 13;
  public static final int tkn_for = 18;
  public static final int tkn_main = 7;
  public static final int tkn_llaveder = 15;
  public static final int tkn_oprel = 6;
  public static final int tkn_llaveiz = 14;
  public static final int tkn_ampersand = 32;
  public static final int tkn_or = 17;
  public static final int EOF = 0;
  public static final int tkn_and = 16;
  public static final int tkn_parentesisiz = 12;
  public static final int tkn_int = 25;
  public static final int error = 1;
  public static final int tkn_void = 8;
  public static final int tkn_opadicion = 2;
  public static final int tkn_if = 9;
  public static final int tkn_id = 27;
  public static final int tkn_while = 10;
  public static final int tkn_scanf = 21;
  public static final int tkn_else = 11;
  public static final int tkn_decrement = 23;
  public static final int tkn_num = 30;
  public static final int tkn_return = 19;
}

