
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 27 11:11:58 CST 2022
//----------------------------------------------------

package Compiladorcito;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tkn_opmulti = 3;
  public static final int tkn_scanf = 23;
  public static final int tkn_comillas = 38;
  public static final int tkn_charp = 9;
  public static final int tkn_int = 27;
  public static final int tkn_for = 20;
  public static final int tkn_main = 6;
  public static final int tkn_comilla = 37;
  public static final int tkn_and = 18;
  public static final int tkn_igual = 7;
  public static final int tkn_coma = 33;
  public static final int tkn_or = 19;
  public static final int tkn_letra = 36;
  public static final int tkn_num = 32;
  public static final int tkn_porcentajed = 34;
  public static final int tkn_dospuntos = 26;
  public static final int tkn_porcentajec = 35;
  public static final int tkn_oprel = 5;
  public static final int tkn_if = 11;
  public static final int tkn_id = 29;
  public static final int tkn_return = 21;
  public static final int tkn_intp = 8;
  public static final int tkn_increment = 24;
  public static final int tkn_else = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int tkn_puntocoma = 30;
  public static final int tkn_printf = 22;
  public static final int tkn_break = 4;
  public static final int tkn_decrement = 25;
  public static final int tkn_digitos = 10;
  public static final int tkn_while = 12;
  public static final int tkn_llaveder = 17;
  public static final int tkn_ternario = 31;
  public static final int tkn_parentesisde = 15;
  public static final int tkn_ampersand = 39;
  public static final int tkn_llaveiz = 16;
  public static final int tkn_char = 28;
  public static final int tkn_parentesisiz = 14;
  public static final int tkn_opadicion = 2;
}

