
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 21 18:41:16 CST 2022
//----------------------------------------------------

package Compiladorcito;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKN_ID = 29;
  public static final int TKN_INT = 27;
  public static final int TKN_IGUAL = 7;
  public static final int TKN_TERNARIO = 31;
  public static final int TKN_WHILE = 12;
  public static final int TKN_SCANF = 23;
  public static final int TKN_CHARP = 9;
  public static final int TKN_DIGITOS = 10;
  public static final int TKN_DOSPUNTOS = 26;
  public static final int TKN_MAIN = 6;
  public static final int TKN_LLAVEIZ = 16;
  public static final int TKN_DECREMENT = 25;
  public static final int TKN_NUM = 33;
  public static final int TKN_PARENTESISDE = 15;
  public static final int TKN_INTP = 8;
  public static final int TKN_BREAK = 4;
  public static final int TKN_RETURN = 21;
  public static final int EOF = 0;
  public static final int TKN_OPADICION = 2;
  public static final int TKN_PRINTF = 22;
  public static final int TKN_PARENTESISIZ = 14;
  public static final int TKN_INCREMENT = 24;
  public static final int error = 1;
  public static final int TKN_ELSE = 13;
  public static final int TKN_SALTO = 32;
  public static final int TKN_OR = 19;
  public static final int TKN_FOR = 20;
  public static final int TKN_OPMULTI = 3;
  public static final int TKN_OPREL = 5;
  public static final int TKN_CHAR = 28;
  public static final int TKN_LLAVEDER = 17;
  public static final int TKN_PUNTOCOMA = 30;
  public static final int TKN_AND = 18;
  public static final int TKN_IF = 11;
}

